import type { ActivityIconKey, ActivityOptionRecord, ActivityOptionType } from "@fitness/shared";

const option = (
  id: string,
  activityType: ActivityOptionType,
  name: string,
  iconKey: ActivityIconKey,
  sortOrder: number,
  aiEligible = true,
  description: string | null = null,
): ActivityOptionRecord => ({
  id,
  activityType,
  slug: id,
  name,
  iconKey,
  aiEligible,
  sortOrder,
  description,
});

export const activityOptions = [
  option("cardio-treadmill-running", "CARDIO", "Treadmill Running", "FOOTPRINTS", 10),
  option("cardio-incline-treadmill-walking", "CARDIO", "Incline Treadmill Walking", "FOOTPRINTS", 20),
  option("cardio-outdoor-running", "CARDIO", "Outdoor Running", "FOOTPRINTS", 30),
  option("cardio-stationary-bike", "CARDIO", "Stationary Bike", "BIKE", 40),
  option("cardio-outdoor-cycling", "CARDIO", "Outdoor Cycling", "BIKE", 50),
  option("cardio-rowing-machine", "CARDIO", "Rowing Machine", "ACTIVITY", 60),
  option("cardio-elliptical", "CARDIO", "Elliptical", "ACTIVITY", 70),
  option("cardio-stair-climber", "CARDIO", "Stair Climber", "FOOTPRINTS", 80),
  option("cardio-air-bike", "CARDIO", "Air Bike", "BIKE", 90),
  option("cardio-jump-rope", "CARDIO", "Jump Rope", "FOOTPRINTS", 100),
  option("cardio-hiking", "CARDIO", "Hiking", "MOUNTAIN", 110),
  option("cardio-ski-erg", "CARDIO", "Ski Erg", "ACTIVITY", 120),

  option("sport-basketball", "SPORT", "Basketball", "CIRCLE_DOT", 10),
  option("sport-soccer", "SPORT", "Soccer", "CIRCLE_DOT", 20),
  option("sport-cricket", "SPORT", "Cricket", "CIRCLE_DOT", 30),
  option("sport-rugby", "SPORT", "Rugby", "CIRCLE_DOT", 40),
  option("sport-boxing", "SPORT", "Boxing", "SWORDS", 50),
  option("sport-golf", "SPORT", "Golf", "TARGET", 60),
  option("sport-swimming", "SPORT", "Swimming", "WAVES", 70),
  option("sport-tennis", "SPORT", "Tennis", "CIRCLE_DOT", 80),
  option("sport-table-tennis", "SPORT", "Table Tennis", "CIRCLE_DOT", 90),
  option("sport-badminton", "SPORT", "Badminton", "CIRCLE_DOT", 100),
  option("sport-bouldering", "SPORT", "Bouldering", "MOUNTAIN", 110),
  option("sport-snowboarding", "SPORT", "Snowboarding", "SNOWFLAKE", 120),
  option("sport-volleyball", "SPORT", "Volleyball", "CIRCLE_DOT", 130),
  option("sport-baseball", "SPORT", "Baseball", "CIRCLE_DOT", 140),
  option("sport-hockey", "SPORT", "Hockey", "CIRCLE_DOT", 150),
  option("sport-martial-arts", "SPORT", "Martial Arts", "SWORDS", 160),
  option("sport-skiing", "SPORT", "Skiing", "SNOWFLAKE", 170),
  option("sport-surfing", "SPORT", "Surfing", "WAVES", 180),
] as const satisfies readonly ActivityOptionRecord[];
